apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432  # Points to the PostgreSQL service
    database: mydb
    user: postgres
    jsonData:
      sslmode: disable
    secureJsonData:
      password: postgres
    isDefault: true
    editable: true