{
 "title": "Sample Dashboard",
 "tags": [ "example" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scrip_id",
    "query": "select scrip_id from my_schema.master_scrips"
   }
  ]
 },
 "panels": [
  {
   "title": "Nifty50 Ticks",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp, open, high, low, last_price \"close\"\r\nfrom my_schema.ticks\r\nwhere instrument_token = 256265\r\norder by timestamp desc\r\n"
    }
   ]
  },
  {
   "title": "Margin/ Cash Available",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 7, "y": 16 },
   "targets": [
    {
     "rawSql": "select margin_type, net, available_cash, available_live_balance\r\nfrom my_schema.margins\r\nwhere run_date = (select max(run_date) from my_schema.margins )\r\nand enabled is True"
    }
   ]
  },
  {
   "title": "Positions",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT fetch_timestamp, position_type, trading_symbol, product, exchange, average_price, pnl FROM my_schema.positions \r\nwhere run_date = (select max(run_date) from my_schema.positions )"
    }
   ]
  },
  {
   "title": "Latest trades",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "select trade_id, order_id, exchange, trading_symbol, transaction_type, quantity, average_price from my_schema.trades\r\nwhere run_date = (select max(run_date) from my_schema.trades )"
    }
   ]
  },
  {
   "title": "Holdings",
   "type": "table",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "select trading_symbol, quantity, average_price, close_price, pnl\r\nfrom my_schema.holdings \r\nwhere run_date = (select max(run_date) from my_schema.holdings)\r\norder by trading_symbol desc"
    }
   ]
  },
  {
   "title": "CandleStick for '$scrip_id' ",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 26 },
   "targets": [
    {
     "rawSql": "select Price_date::timestamp \"Date\", Price_open \"Open\", price_high \"High\", price_low \"Low\", price_close \"Close\", volume\r\nfrom my_schema.rt_intraday_price rip \r\nwhere rip.scrip_id = upper('$scrip_id') \r\norder by rip.price_date desc"
    }
   ]
  }
 ]
}